define(['angular', 'app'], function (angular, app) {
  app.constant('constants', {
    ASSIGNED_STATUS: "Assigned",
    CANCELLED_STATUSD: "Cancelled",
    COMPLETED_STATUS: "Completed",
    COURSE_TYPE: "course",
    CURRICULUM_TYPE: "curriculum",
    EMPTY_STATUS: "",
    FAILED_STATUS: "Failed",
    IN_PROGRESS_STATUS: "In Progress",
    LEARNING_PATH_TYPE: "learningPath",
    MODULE_TYPE: "module",
    NOT_STARTED_STATUS: "Not Started",
    ORDER_BY_COMPLETION: "completion",
    ORDER_BY_DUE_DATE: "dueDate",
    ORDER_BY_DURATION: "duration",
    ORDER_BY_SEQUENCE: "sequence",
    ORDER_BY_STATUS: "statusOrder",
    ORDER_BY_TITLE: "title",
    ORDER_BY_TITLE_ASCENDING: "titleAscending",
    ORDER_BY_TITLE_DESCENDING: "titleDescending",
    ORDER_BY_TYPE: "objectTypeOrder",
    PASSED_STATUS: "Passed",
    PAST_DUE_STATUS: "Past Due",
    QUIZ_TYPE: "quiz",
    RETIRED_STATUS: "Retired",
    UNENROLLED_STATUS: "Unenrolled",
    MY_LEARNING_PAGE: 'myLearningPage',
    FIND_LEARNING_PAGE: 'findLearningPage',
    COMPLETED_LEARNING_PAGE: 'completedLearningPage',
    CONTAINER_DETAILS_PAGE: 'containerDetailsPage',
    MODULE_DETAILS_PAGE: 'moduleDetailsPage',
    ERROR_PAGE: 'errorPage',
    QUIZ_PAGE: 'quizPage',
    RESULT_SINGLE: 'Result',
    RESULT_MULTIPLE: 'Results',
    LEARNING_OBJECT_SINGLE: 'Learning Object',
    LEARNING_OBJECT_MULTIPLE: 'Learning Objects',
    SHOW_MESSAGE: 'showMessage',
    QUESTION_TYPE_MULTI_SELECT: 'Multi Select',
    QUESTION_TYPE_TRUE_FALSE: 'True/False',
    QUESTION_TYPE_FREE_TEXT: 'Free Text',
    QUESTION_TYPE_SINGLE_SELECT: 'Single Select',
    QUESTION_TYPE_PAGE_BREAK: 'Page Break',
    QUESTION_NO_TYPE: 'Empty Type',
    ACCESS_DENIED: 'accessDenied'
  });
});