function copyInnerHTML(a,b){b.innerHTML=a.innerHTML}function listProperties(a){var b="",c;for(c in a)b+=c+", ";alert(b)}function getLocalOffsetTop(a){return getLocalOffset(a,"Top")}function getLocalOffsetLeft(a){return getLocalOffset(a,"Left")}function getLocalOffset(a,b){var c=a["offset"+b],d;try{d=a.offsetParent}catch(e){return c}for(;d&&"static"==getCurrentStyle(d,"position");){c+=d["offset"+b];try{d=d.offsetParent}catch(f){break}}return c}
function makeAjaxRequest(a,b){if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest;else if(window.ActiveXObject)xmlhttp=new ActiveXObject("MSXML2.XMLHTTP");else return!1;xmlhttp.open("GET",a,!0);xmlhttp.onreadystatechange=function(){4==xmlhttp.readyState&&b&&b(xmlhttp.responseText)};xmlhttp.send(null)}
function getElementsByClassName(a,b,c){b||(b=document.body);if(b.getElementsByClassName){var d=b.getElementsByClassName(a);if(strTagNameUpper=c?c.toUpperCase():null){if(Array.filter)return Array.filter(d,function(a){return a.nodeName==strTagNameUpper});c=[];a=d.length;for(b=0;b<a;b++)d[b].nodeName==strTagNameUpper&&c.push(d[b]);return c}return d}c||(c="*");for(var d="*"==c&&b==document.body&&document.all?document.all:b.getElementsByTagName(c),c=[],a=a.replace(/\-/g,"\\-"),e=RegExp("\\b"+a+"\\b"),
a=d.length,b=0;b<a;b++)e.test(d[b].className)&&c.push(d[b]);return c}function getLoginCookieValue(){var a=document.cookie,b=a.indexOf("login=");if(-1==b)return"";var b=b+6,c=a.indexOf(";",b);-1==c&&(c=a.length);return a.substring(b,c)}function assureInt(a){var b;return isNaN(b=parseInt(a))?0:b}
var isIE=-1!=navigator.appName.indexOf("Microsoft"),isIE5=0<navigator.userAgent.indexOf("MSIE 5.0"),isIE7=-1!=navigator.userAgent.indexOf("MSIE 7"),isOpera=-1!=navigator.userAgent.indexOf("Opera"),isSafari=-1!=navigator.userAgent.indexOf("AppleWebKit"),isFirefox=-1!=navigator.userAgent.indexOf("Firefox/"),isNetscape=-1!=navigator.userAgent.indexOf("Netscape/"),lastMouseX,lastMouseY,curPopupWindow=null,closeOnParentUnloadWindow=null,helpWindow=null,win=null,editPage=!1,currentEntityId="",currentEntityId2=
"",picklistNAMarker="_\u0001_";function EventData(a,b,c,d){this.element=a;this.type=b;this.handler=c;this.useCapture=d}
var eventRegistry,addEvent=function(){return window.addEventListener?function(a,b,c,d){a.addEventListener(b,c,d);eventRegistry||(eventRegistry=[],window.addEventListener("unload",cleanupEvents,!1));eventRegistry.push(new EventData(a,b,c,d))}:window.attachEvent?function(a,b,c){var d=a.attachEvent("on"+b,c);eventRegistry||(eventRegistry=[],window.attachEvent("onunload",cleanupEvents));eventRegistry.push(new EventData(a,b,c));return d}:function(){return null}}(),removeEvent=function(){return window.removeEventListener?
function(a,b,c,d){a.removeEventListener(b,c,d)}:window.detachEvent?function(a,b,c){a.detachEvent("on"+b,c)}:function(){return null}}();function cleanupEvents(){if(eventRegistry){for(var a=0;a<eventRegistry.length;a++){var b=eventRegistry[a];removeEvent(b.element,b.type,b.handler,b.useCapture)}eventRegistry=null;removeEvent(window,"unload",cleanupEvents,!1)}}function mouseExited(a,b){for(var c=getEventToElement(a);c&&c!=document.body;){if(c==b)return!1;c=c.parentNode}return!0}
function getEvent(a){return a||window.event}function getEventTarget(a){return window.event?a.srcElement:a.target}function getEventToElement(a){return a.relatedTarget?a.relatedTarget:a.toElement}function eventCancelBubble(a){a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation()}var beenFocused=!1,focusedElement=null,textAreaTimer=null;function markFocused(){beenFocused=!0}addEvent(document,"mousedown",markFocused);function trackFocused(a){a||(a=window.event);focusedElement=a&&a.target||null}
addEvent(document,"focus",trackFocused);function reFocus(){if(focusedElement&&focusedElement.focus){var a=focusedElement.id;if(a){for(var b=reFocus.arguments,c=0;c<b.length;c+=2)if(a==b[c]){a=document.getElementById(b[c+1]);hiddenOrDisabled(a)||a.focus();focusedElement=a;return}if((a=document.getElementById(a))&&a.focus&&!hiddenOrDisabled(a))a.focus(),focusedElement=a}}}
function setEntityInformation(a,b,c,d,e,f,g){currentEntityId=d;currentEntityId2=g;g=self.getAccessibleParentWindow?getAccessibleParentWindow(self):self;editPage=e;f&&g&&(g.sendCTIMessage&&g.sendCTIMessage("ADD_LOG_OBJECT?ID="+d+"&OBJECT_LABEL="+escape(b)+"&ENTITY_NAME="+c+"&OBJECT_NAME="+escape(a)),g.cleanupClickToDial&&g.cleanupClickToDial());if(g&&g.Sfdc&&(b=g.Sfdc.ns("Sfdc.support.api"),b.pageInfo=b.pageInfo||{},b.pageInfo[d]={url:location.href,objectId:d,objectName:a,object:c},g.Sfdc.interaction&&
(g.Sfdc.interaction.currentEntityId=d,g.Sfdc.interaction.isListenerEnabled.onFocus&&g.Sfdc.support.api.pageInfo[d])))g.Sfdc.interaction.onFocus()}function setLastMousePosition(a){-1!=navigator.appName.indexOf("Microsoft")&&(a=window.event);lastMouseX=a.screenX;lastMouseY=a.screenY}function openClickout(a){openClickoutWithSize(a,640,480)}
function openClickoutWithSize(a,b,c){window.open(a,"_blank","width="+b+",height="+c+",dependent=no,resizable=yes,toolbar=yes,status=yes,directories=yes,menubar=yes,scrollbars=1",!1)}function openIntegration(a,b,c){a=window.open(a,"_blank",b,!1);2==c?a.moveTo(0,0):0==c&&(a.moveTo(0,0),a.resizeTo(self.screen.width,self.screen.height))}function openPopup(a,b,c,d,e,f){openPopupFocus(a,b,c,d,e,f,!0)}function openPopupFocusEscapePounds(a,b,c,d,e,f,g){openPopupFocus(a.replace("#","%23"),b,c,d,e,f,g)}
function openPopupFocus(a,b,c,d,e,f,g,k){closePopup();f&&(0>lastMouseX-c&&(lastMouseX=c),lastMouseY+d>screen.height&&(lastMouseY-=lastMouseY+d+50-screen.height),lastMouseX-=c,lastMouseY+=10,e+=",screenX="+lastMouseX+",left="+lastMouseX+",screenY="+lastMouseY+",top="+lastMouseY);g?(curPopupWindow=window.open(a,b,e,!1),curPopupWindow.focus()):(win=window.open(a,b,e,!1),win.focus());k&&(closeOnParentUnloadWindow=win)}
function openPopupFocusWithOffset(a,b,c,d){win=window.open(a,"",b);win.moveTo(window.pageXOffset+c,window.pageYOffset+d);win.focus()}var closetimer,ie9=0<=navigator.userAgent.indexOf("MSIE 9");function closePopupOnBodyFocus(){ie9?(closetimer&&clearTimeout(closetimer),closetimer=window.setTimeout(function(){closetimer=null;closePopup()},500)):closePopup()}
function closePopup(){closetimer&&(clearTimeout(closetimer),closetimer=null);if(null!=curPopupWindow){try{if(curPopupWindow.confirmOnClose&&curPopupWindow.confirm(curPopupWindow.confirmOnCloseLabel))return curPopupWindow.confirmOnClose=!1,curPopupWindow.focus(),!1;curPopupWindow.close()}catch(a){}curPopupWindow=null}}var modalWindow=null;function ignoreModalEvents(){return!1}
function handleModalFocus(){modalWindow&&(modalWindow.closed?(window.top.releaseEvents(Event.CLICK|Event.FOCUS),window.top.onclick=""):modalWindow.focus());return!1}function invokeResultFunc(){(window.dialogArguments?window.dialogArguments:window.opener.resultFunc)()}
function openPopupModal(a,b,c,d,e,f,g){if(window.showModalDialog)window.showModalDialog(a,null==f?window:f,e);else if(window.top.captureEvents)window.top.captureEvents(Event.CLICK|Event.FOCUS),window.top.onclick=ignoreModalEvents,window.top.onfocus=handleModalFocus,modalWindow=window.open(a,b,e+",modal=yes"),f&&(window.resultFunc=f);else return g?g():openPopup(a,b,c,d,e,!1)}var clickedLink,warningText;
function confirmPopup(a,b,c,d,e,f){clickedLink=e.href?e.href:e;warningText=f;e=new Function("window.location = clickedLink");e.window=window;openPopupModal(a,"_blank",b,c,d,e,new Function("return confirm(warningText)"));return!1}function openLookup(a,b,c,d){"1"==c&&(a+=d);openPopup(a,"lookup",350,480,"width="+b+",height=480,toolbar=no,status=no,directories=no,menubar=no,resizable=yes,scrollable=no",!0)}
function pick(a,b,c,d){document.getElementById(a)[b].value=c;if(d)document.getElementById(a)[b].onchange();closePopup();return!1}function pickSubmit(a,b,c,d){document.getElementById(a)[b].value=c;if(d)document.getElementById(a)[b].onchange();document.getElementById(a).submit();closePopup();hiddenOrDisabled(document.getElementById(a)[b])||(document.getElementById(a)[b].focus(),document.getElementById(a)[b].select());return!1}
function hiddenOrDisabled(a){do{if(null==a||"hidden"==a.type||a.disabled||"none"==getCurrentStyle(a,"display")||"hidden"==getCurrentStyle(a,"visibility"))return!0;a=a.parentNode}while(null!=a&&"BODY"!=a.tagName);return!1}function hiddenOrDisabledOrReadOnly(a){do{if(null==a||"hidden"==a.type||a.readOnly||a.disabled||"none"==getCurrentStyle(a,"display")||"hidden"==getCurrentStyle(a,"visibility"))return!0;a=a.parentNode}while(null!=a&&"BODY"!=a.tagName);return!1}
function pickcolor(a,b,c){var d=parseInt(c,16),a=document.getElementById(a)[b];a.setValue?a.setValue(d):a.value=d;document.getElementById(b+"cell").style.backgroundColor="#"+c;closePopup();return!1}function comboBoxPick(a,b,c,d){a=document.getElementById(a)[b];null!=a&&(c=eval(c),null!=c&&(0<=d&&d<c.length)&&(a.value=c[d],hiddenOrDisabled(a)||(a.focus(),a.select())));closePopup();return!1}
function attachEventToElement(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function navigateToUrl(a){window.location=a}
function hitUrl(a){var b=document.getElementsByTagName("body")[0],c=document.getElementById("goToUrlFrame");c||(c=document.createElement("div"),c.style.display="none",b.appendChild(c),c.innerHTML='<iframe src="javascript:false" style="display:none;" id="goToUrlFrame" name="goToUrlFrame"></iframe>',c=document.getElementById("goToUrlFrame"),c.title="blank - ignore");c=document.createElement("form");b.appendChild(c);c.target="goToUrlFrame";c.method="POST";c.action=a;c.submit();b.removeChild(c)}
function doLookupPick(a,b,c,d,e,f,g,k,l){var h=b.parentIdElement,j=b.parentEditElement,m=j.name,n=b.parentEditOldValueElement;if("select-one"==h.type){e=!1;for(i=0;i<h.options.length;i++)if(h.options[i].value==c){h.selectedIndex=i;e=!0;break}e||(h.options[h.options.length]=new Option(d,c),h.selectedIndex=h.options.length-1);j.value=d;n.value=d;!hiddenOrDisabled(h)&&"function"==typeof h.onchange&&(c=h.value,window.Sfdc&&(Sfdc.Event&&Sfdc.Event.fireEvent)&&Sfdc.Event.fireEvent(h,"change"),h.value=c,
j.value=d)}else{if(b.extraNameElement)if(f){if("undefined"!==typeof b.extraNameElement.value&&(0==b.extraNameElement.value.length||b.extraNameElement.value==j.value))b.extraNameElement.value=d}else if((e||null==b.extraNameElement.value||""==b.extraNameElement.value)&&null!=k&&""!=k)if(b.extraNameElement.value=k,b.extraIdElement&&(b.extraIdElement.value=l),b.extraEditOldValueElement)b.extraEditOldValueElement.value=k;h.value=c;j.value=d;n.value=d;window.ForeignKeyInputElement&&ForeignKeyInputElement.dispatchLookupChange(j.name);
window.sfdcPage&&sfdcPage.getFieldById&&(n=sfdcPage.getFieldById(j.name))&&n.lookupPickCalled();!hiddenOrDisabled(j)&&"function"==typeof j.onchange&&(window.Sfdc&&(Sfdc.Event&&Sfdc.Event.fireEvent)&&Sfdc.Event.fireEvent(j,"change"),h.value=c,j.value=d)}b.relatedFieldElement&&(b.relatedFieldElement.value=g);var o=getElementByIdCS(m+"_onpk");o&&""!=o.value&&setTimeout(function(){eval(o.value)},1);if((d=getElementsByNameCS(m+"_lspf")[0])&&"1"==d.value){if(m=getElementsByNameCS(m+"_lspfsub")[0])m.value=
"1";document[a].submit()}b.modElement&&(b.modElement.value="1");closePopup();hiddenOrDisabled(j)||(j.focus(),j.select());return!1}
function lookupPick(a,b,c,d,e,f,g,k){function l(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c].getAttribute("name")===b)return a[c]}var h=document.forms[a],b={parentIdElement:l(Sfdc.select(Sfdc.String.format("input[name='{name}'], select[name='{name}']",{name:b}),h),b),parentEditElement:l(Sfdc.select(Sfdc.String.format("input[name='{name}'], select[name='{name}']",{name:c}),h),c),parentEditOldValueElement:l(Sfdc.select(Sfdc.String.format("input[name='{name}'], select[name='{name}']",{name:c+"_lkold"}),
h),c+"_lkold"),relatedFieldElement:getElementsByNameCS(d)[0],extraNameElement:getElementsByNameCS(k)[0],modElement:getElementsByNameCS(c+"_mod")[0]};return doLookupPick(a,b,e,f,!1,!0,g)}
function lookupPick2(a,b,c,d,e,f,g,k,l,h){function j(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c].getAttribute("name")===b)return a[c]}var m=document.forms[a],b={parentIdElement:j(Sfdc.select(Sfdc.String.format("input[name='{name}'], select[name='{name}']",{name:b}),m),b),parentEditElement:j(Sfdc.select(Sfdc.String.format("input[name='{name}'], select[name='{name}']",{name:c}),m),c),parentEditOldValueElement:j(Sfdc.select(Sfdc.String.format("input[name='{name}'], select[name='{name}']",{name:c+"_lkold"}),
m),c+"_lkold"),extraNameElement:getElementsByNameCS(f)[0],extraIdElement:getElementsByNameCS(k)[0],extraEditOldValueElement:getElementsByNameCS(f+"_lkold")[0],modElement:getElementsByNameCS(c+"_mod")[0]};return doLookupPick(a,b,d,e,h,!1,null,g,l)}function searchEntityTwo(a,b,c){b=document.getElementById(b);if(a){if(b.checked=!0,a=document.getElementsByName(c))for(i=0;i<a.length;++i)a[i]!=b&&(a[i].checked=!1)}else b.checked=!1}
function lookupPhonePick(a,b){var c=document.getElementById(a);c.value=b;closePopup();c.focus();c.select()}function setFocusOnLoad(){beenFocused||setFocus()}function elementFocus(a){hiddenOrDisabled(a)||a.focus()}function elementSelect(a){hiddenOrDisabled(a)||a.select()}
function setFocus(){for(var a=1;5>a;a++)for(var b=a,c=0;c<document.forms.length;c++)for(var d=document.forms[c],e=0;e<d.elements.length;e++){var f=d.elements[e];if(f.tabIndex==b){if(("text"==f.type||"textarea"==f.type||"password"==f.type)&&!hiddenOrDisabledOrReadOnly(f)&&"sbstr"!=f.name&&0!=f.name.indexOf("owner")&&0!=f.name.indexOf("tsk1")&&0!=f.name.indexOf("evt1")&&"tsid"!==f.name)return f.focus(),"text"==f.type&&f.select(),!0;b++;e=0}}for(c=0;c<document.forms.length;c++)if(d=document.forms[c],
a=d.name,"sbsearch"!=a&&"srch_solution_sbar"!=a&&"srch_product_sbar"!=a&&"srch_document_sbar"!=a&&"srch_article_sbar"!=a)for(e=0;e<d.elements.length;e++)if(f=d.elements[e],("text"==f.type||"textarea"==f.type||"password"==f.type)&&!hiddenOrDisabledOrReadOnly(f)&&0!=f.name.indexOf("owner")&&"tsid"!==f.name)return f.focus(),"text"==f.type&&f.select(),!0;return!0}
function setNamedFocus(a){for(var b=0;b<document.forms.length;b++)for(var c=document.forms[b],d=0;d<c.elements.length;d++){var e=c.elements[d];if(e.name==a&&!hiddenOrDisabled(e))return e.focus(),"text"==e.type&&!hiddenOrDisabled(e)&&e.select(),!0}return!0}function formatPhoneOnEnter(a,b){getEvent(b).keyCode==KEY_ENTER&&formatPhone(a)}
function formatPhone(a){a.value=trim(a.value);var b=a.value,c="",d=-1;if(0<b.length&&"+"!=b.charAt(0)){var e=0;"1"==b.charAt(0)&&(b=b.substring(1,b.length));for(i=0;i<b.length;i++){var f=b.charAt(i);"0"<=f&&"9">=f&&(0==e?c+="(":3==e?c+=") ":6==e&&(c+="-"),c+=f,e++);if(!("0"<=f&&"9">=f)&&" "!=f&&"-"!=f&&"."!=f&&"("!=f&&")"!=f){d=i;break}}0<=d&&(c+=" "+b.substring(d,b.length));10==e&&40>=c.length&&(a.value=c)}return!0}
function clearcols(){for(var a=0;a<document.forms.length;a++)for(var b=0;b<document.forms[a].elements.length;b++){var c=document.forms[a].elements[b];if("c"==c.name||"c_"==c.name.substring(0,2))c.checked=!1}}function setcols(){for(var a=0;a<document.forms.length;a++)for(var b=0;b<document.forms[a].elements.length;b++){var c=document.forms[a].elements[b];if("c"==c.name||"c_"==c.name.substring(0,2))c.checked=!0}}
function setUsername(a,b,c,d){0==a.value.length&&(a.value=b.value.substring(0,1).toLowerCase()+c.value.toLowerCase()+"@"+d.value)}function setAlias(a,b,c){0==a.value.length&&(a.value=b.value.substring(0,1).toLowerCase()+c.value.substring(0,4).toLowerCase())}function popWin(a){closePopup();curPopupWindow=window.open(a,"win","toolbar=0,location=0,directories=0,status=0,menubar=0,scrollbars=1,resizable=0,width=550,height=300",!1)}
function popWin2(a){win=window.open(a,"win","toolbar=0,location=0,directories=0,status=0,menubar=0,scrollbars=1,resizable=0,width=720,height=500",!1)}function adminWin(a){win=window.open(a,"win","toolbar=1,location=1,directories=0,status=1,menubar=1,scrollbars=1,resizable=1,width=800,height=600",!1)}function printWin(a){popWin=window.open(a,"win","dependent=no,toolbar=1,directories=0,location=0,status=1,menubar=1,scrollbars=1,resizable=1,width=705,height=400",!1);popWin.focus()}
function moveSelectElement3(a,b,c,d,e){if(-1<a.selectedIndex){for(i=0;i<a.length;++i){var f=a.options[i];if(f.selected)if(f.text!=c){var g=new Option(f.text,f.value);g.title=f.title;0<b.options.length&&b.options[0].text==d?(b.options[0]=g,b.selectedIndex=0):(b.options[b.options.length]=g,b.selectedIndex=b.options.length-1)}else a.selectedIndex=-1}e||removeSelectElement3(a,c)}}function sortOrderNumeric(a,b){return a-b}function sortOrderNumericReverse(a,b){return b-a}
function moveSelectElementIds(a,b,c,d,e){if(c){b=b.options;for(i=0;i<c.length;i++){var f=a.options[c[i]],g=new Option(f.text,f.value);g.title=f.title;1==b.length&&b[0].text==e?(b[0]=g,b[0].selected=!0):b[b.length]=g}if(!d){c=c.sort(sortOrderNumericReverse);for(i=0;i<c.length;i++)a.options[c[i]]=null;0==a.length&&(c=new Option(e,e),a.options[0]=c)}}}function moveOption(a,b,c,d,e,f,g,k,l){DuelingListBoxesElement.moveOption(a,b,c,d,e,f,g,k,l)}
function removeSelectElement3(a,b){if(-1<a.selectedIndex){for(i=a.length-1;-1<i;i--)a.options[i].selected&&(a.options[i]=null);if(0==a.length){var c=new Option(b,b);a.options[0]=c}}}function moveUp(a,b,c,d,e){return DuelingListBoxesElement.moveUp(a,b,c,d,e)}function moveDown(a,b,c,d,e){return DuelingListBoxesElement.moveDown(a,b,c,d,e)}function moveTop(a,b){return DuelingListBoxesElement.moveTop(a,b)}function moveBottom(a,b){DuelingListBoxesElement.moveBottom(a,b)}
function saveAllSelected(a,b,c,d,e){DuelingListBoxesElement.saveAllSelected(a,b,c,d,e)}function ddChangeAllElements(a,b){var c=a.selectedIndex;if(0<c)for(var d=0;d<b.length;d++){var e=getElementByIdCS(b[d]);e&&(e.selectedIndex=c-1)}}function ddElementChange(a,b,c){for(var a=getElementByIdCS(b[0]).selectedIndex,d=1;d<b.length;d++)if(getElementByIdCS(b[d]).selectedIndex!=a){a=-1;break}getElementByIdCS(c).selectedIndex=a+1}
function ddRadioClicked(a,b,c){a="all"==a.value;document.getElementById(c).disabled=!a;for(var d=0;d<b.length;d++){var e=getElementByIdCS(b[d]);e&&(e.disabled=a);if(a){var f=getElementByIdCS(c).selectedIndex;0<f&&(e.selectedIndex=f-1)}}}
function openwizard(a,b,c){b=window.open("",b,"toolbar=0,location=0,directories=0,status=0,menubar=0,scrollbars=1,resizable="+c+",width=700,height=550,screenx=50,screeny=10,left=50,top=10",!1);if(""==b.document.URL||"about:blank"==b.document.URL)b.location=a;b.focus()}function openwizard2(a,b,c){window.open(a,b,"toolbar=0,location=0,directories=0,status=0,menubar=0,scrollbars=1,resizable="+c+",width=700,height=550,screenx=50,screeny=10,left=50,top=10",!1)}
function escapeUTF(a){var b="";for(i=0;i<a.length;i++){var c=a.charCodeAt(i);127>=c?b+=escape(a.charAt(i)):2047>=c?b+="%"+(c>>6|192).toString(16)+"%"+(c&63|128).toString(16):2048<=c&&(b+="%"+(c>>12|224).toString(16)+"%"+(c>>6&63|128).toString(16)+"%"+(c&63|128).toString(16))}return b}function openRefer(a){window.open(a,"referv2","resizable=no,toolbar=no,status=no,directories=no,scrollbars=yes,width=420,height=500",!1)}
function changeOpenerWindowLocation(a){null==window.top.opener||window.top.opener.closed?window.top.open(a):(window.top.opener.location.href=a,window.top.opener.focus())}function verifyUnderLimit(a,b,c,d){var e=0;for(i=0;i<a.elements.length;i++)if(a.elements[i].name==b&&a.elements[i].checked&&++e>c)return alert(d),!1;return!0}function verifyChecked(a,b,c){for(i=0;i<a.elements.length;i++)if(a.elements[i].name==b&&a.elements[i].checked)return!0;alert(c);return!1}
function verifyCheckedByPrefix(a,b,c){for(i=0;i<a.elements.length;i++)if(0==a.elements[i].name.indexOf(b)&&a.elements[i].checked)return!0;alert(c);return!1}function verifySingleCheckedByPrefix(a,b,c){var d=0;for(i=0;i<a.elements.length;i++)0==a.elements[i].name.indexOf(b)&&a.elements[i].checked&&d++;if(1==d)return!0;alert(c);return!1}function verifyCheckedWarning(a,b,c){var d=!1;for(i=0;i<a.elements.length;i++)a.elements[i].name==b&&a.elements[i].checked&&(d=!0);return d?window.confirm(c):!0}
function submitFormActionURL(a,b){a.action=b;a.submit()}function updateToggleAllBox(a,b,c){var d=null;"undefined"!=typeof c?d=document.getElementById(c):a.allBox&&(d=a.allBox);null!=d&&(d.checked=allChecked(a,b))}function allChecked(a,b){for(var c=0,c=0;c<a.elements.length;c++){var d=a.elements[c];if(d.name==b&&"checkbox"==d.type&&!1==d.checked)return!1}return!0}
function SelectChecked(a,b,c){for(var d=0,d=0;d<a.elements.length;d++)a.elements[d].name==b&&!1==a.elements[d].disabled&&(a.elements[d].checked=c)}function SelectAllOrNoneByCheckbox(a,b,c){for(var d=c.parentNode;d&&"form"!==d.tagName;)d=d.parentNode;null!=d&&(a=d);SelectChecked(a,b,c.checked)}
function loader(){var a=getCookie("login");0<a.length?(document.login_noop.un_noop.value=a,document.login.un.value=a,document.login.pw.focus()):document.login_noop.un_noop.focus();document.login.width.value=screen.width;document.login.height.value=screen.height}function handleSelectAllNoneCheckboxClick(a,b){for(var c=0;c<b.length;c++){var d=document.getElementById(b[c]);d&&(d.checked=a.checked)}}function getObjX(a){for(var b=0;null!=a;)b+=a.offsetLeft,a=a.offsetParent;return b}
function getObjY(a){for(var b=0;null!=a;)b+=a.offsetTop,a=a.offsetParent;return b}function getScrollX(){if(window.pageXOffset)return window.pageXOffset;if(document.documentElement&&document.documentElement.scrollLeft)return document.documentElement.scrollLeft;if(document.body.scrollHeight)return document.body.scrollLeft}
function getScrollY(){if(window.pageYOffset)return window.pageYOffset;if(document.documentElement&&document.documentElement.scrollTop)return document.documentElement.scrollTop;if(document.body.scrollWidth)return document.body.scrollTop}function getMouseX(a){return a.pageX?a.pageX:getScrollX()+a.clientX}function getMouseY(a){return a.pageY?a.pageY:getScrollY()+a.clientY}function getSrcElement(a){a=getEvent(a);return a.srcElement?a.srcElement:a.currentTarget}
function ltrim(a){return a.replace(/^\s*/,"")}function rtrim(a){return a.replace(/\s*$/,"")}function trim(a){return rtrim(ltrim(a))}function escapeHTML(a){a&&a.replace&&(a=a.replace(/&/g,"&amp;"),a=a.replace(/</g,"&lt;"),a=a.replace(/>/g,"&gt;"));return a}function unescapeHTML(a){a&&a.replace&&(a=a.replace(/\&amp;/g,"&"),a=a.replace(/&lt;/g,"<"),a=a.replace(/&gt;/g,">"));return a}
function unescapeJsInHtml(a){a&&a.replace&&(a=a.replace(/\\\\/g,"\\"),a=a.replace(/\\'/g,"'"),a=a.replace(/\\n/g,"\n"),a=a.replace(/&quot;/g,'"'));return a}function unescapeXML(a){a&&a.replace&&(a=a.replace(/\&amp;/g,"&"),a=a.replace(/&lt;/g,"<"),a=a.replace(/&gt;/g,">"),a=a.replace(/&quot;/g,'"'),a=a.replace(/&apos;/g,"'"));return a}
function isValidEmail(a,b){if(!a)return!1;var a=a.toLowerCase(),c=a.split("@");if(2!=c.length||0>c[1].indexOf("."))return!1;if(b){for(var d=b.split(","),e=0;e<d.length;e++){var f=d[e];if(c[1]==f||0<c[1].indexOf(f,c[1].length-f.length)&&"."==c[1].charAt(c[1].length-f.length-1))return!0}return!1}return!0}
function isValidDomain(a){if(!/^[a-zA-Z0-9\-\.]+$/.test(a)||0>a.indexOf(".")||0<=a.indexOf("..")||(0<=a.indexOf(".-")||0<=a.indexOf("-."))||("."==a.charAt(0)||"-"==a.charAt(0))||("."==a.charAt(a.length-1)||"-"==a.charAt(a.length-1))||"localhost.localdomain"==a.toLowerCase())return!1;a=a.split(".");return!a||2>a.length||0==a[0].length||1>=a[1].length?!1:!0}
function setCookie(a,b,c,d,e){document.cookie=a+"="+(e?encodeURIComponent:escape)(b)+(c?"; expires="+c.toGMTString():"")+(d?"; path="+d:"; path=/")}function getCookie(a){var b=document.cookie,a=a+"=",c=b.indexOf("; "+a);if(-1==c){if(c=b.indexOf(a),0!=c)return null}else c+=2;var d=document.cookie.indexOf(";",c);-1==d&&(d=b.length);return unescape(b.substring(c+a.length,d))}
function deleteCookie(a,b){if(getCookie(a)){var c=new Date((new Date).getTime()+-1E4);document.cookie=a+"=-deleted-"+(b?"; path="+b:"; path=/")+"; expires="+c.toGMTString()}}function addTwistCookie(a,b,c){var d=getCookie(a),c=b+":"+(c?"1":"0")+",";if(d){for(var e=d.indexOf(b);-1<e;){var f=e+18;d.substring(e,f);d=d.substring(0,e)+d.substring(f,d.length);e=d.indexOf(b)}c=d+c}setCookie(a,c)}
function handleTextAreaElementChange(a,b,c,d){textAreaTimer&&clearTimeout(textAreaTimer);textAreaTimer=setTimeout(function(){return handleTextAreaElementChangeWithByteCheck(a,b,0,c,d)},500)}
function handleTextAreaElementChangeWithByteCheck(a,b,c,d,e){var f=document.getElementById(a),a=document.getElementById(a+"_counter"),g=0;if(!f||!a)return b;var k=f.value.length;if(0<k&&!isIE&&!isIE5){var l=f.value.match(/\n/g);l&&(g=l.length)}b-=k+g;50<b&&0<c&&(k=unescape(encodeURIComponent(f.value)).length,c-=k+g,50>c&&(b=c));0>b?(a.parentNode.className="textCounterMiddle over",a.innerHTML=-1*b+" "+e):50>b?(a.parentNode.className="textCounterMiddle warn",a.innerHTML=b+" "+d):a.parentNode.className=
"textCounterMiddle"}var filterLookupValueElem;
function openFilterLookupWindow(a,b,c,d){filterLookupValueElem=d;c=document.getElementById(c);c="number"==typeof c.selectedIndex?c.options[c.selectedIndex]:c;if(null!=a||null==b){var a=document.getElementById(a),d=a.action,e=a.target,f=a.lookup.value;null!=b&&(a.action=b);a.target="filter_lookup";a.lookup.value=c.value;a.submit();a.action=d;a.target=e;a.lookup.value=f}else a=0<=b.indexOf("?")?"&":"?",curPopupWindow.location.href=b+a+"lookup="+c.value+"&workflow=1"}
function submitCalcAgg(a,b){var c=document.report;c||(c=opener.document.report);c.target="aggcalc_popup";c.calcagg_request.value=a;c.calcagg_index.value=b;if("new"==a)clearCalcAgg(c,"_v");else if("edit"==a)copyCalcaggParams(c,b,c,"_v");else if("done"==a||"validate"==a){var d=document.getElementById("calcagg_form");copyCalcaggParams(d,"_v",c,"_v")}c.nav.value="agg";c.submit();c.calcagg_request.value="";c.target=""}
function finishValidCalcAgg(a){var b=opener.document.getElementById("report"),c=document.getElementById("calcagg_form");b.calcagg_index.value=a;copyCalcaggParams(c,"_v",b,a);b.calcagg_active_v.value=c.calcagg_name_v.value;b.nav.value="agg";b.submit();self.close()}var calcagg_params="calcagg_label calcagg_name calcagg_formula calcagg_type calcagg_desc calcagg_scale".split(" ");function clearCalcAgg(a,b){for(var c in calcagg_params)a[calcagg_params[c]+b].value=""}
function deleteCalcAgg(a){var b=document.getElementById("report");clearCalcAgg(b,a);b.nav.value="agg";b.submit()}function copyCalcaggParams(a,b,c,d){for(var e in calcagg_params)c[calcagg_params[e]+d].value=a[calcagg_params[e]+b].value}function getIframeContents(a){return(a.contentDocument||a.contentWindow.document).body.innerHTML}
function adjustIFrameSize(a){if(a){var b;a.contentDocument?b=a.contentDocument.body.offsetHeight:(b=document.frames&&document.frames(a.id)?document.frames(a.id).document.body:a.document.body,b=0>=b.children.length?0:b.scrollHeight);var c=a.height-b;0>c&&(c=-c);15<c&&(a.height=b)}}function showTextStateField(a,b){a.style.display="";b.style.display="none"}
function showPicklistStateField(a,b,c){var d=a[0],a=a[1];c.options.length=1;for(i=0;i<d.length;i++)c.options[i+1]=new Option(d[i],a[i]);b.style.display="none";c.style.display=""}function showStateListForCountry(a,b,c,d){a=b[a];c.value="";a?showPicklistStateField(a,c,d):showTextStateField(c,d)}
function scaleImage(a,b,c){if(Sfdc.userAgent.isIE7&&0===a.width)setTimeout(function(){scaleImage(a,b,c)},10);else{var d=a.width*b/a.height,e=b;d>c&&(d=c,e=a.height*c/a.width);if(d<a.width||e<a.height)a.width=d,a.height=e;Sfdc.userAgent.isIE7&&(a.style.visibility="visible")}}function refreshWizardPage(a){var b=document.getElementById("goRefresh");"goRefresh"!=b.value&&(b.value="goRefresh",b=document.getElementById("stageForm"),b.action+=a,b.submit())}
function getOffsetLeft(a){if(!a)return 0;for(var b=a.offsetLeft;a.offsetParent;)a=a.offsetParent,b+=a.offsetLeft;return b}function getWindowWidth(){if("number"==typeof window.innerWidth)return window.innerWidth;if(document.documentElement&&document.documentElement.clientWidth)return document.documentElement.clientWidth;if(document.body&&document.body.clientWidth)return document.body.clientWidth}
function getWindowHeight(){if("number"==typeof window.innerHeight)return window.innerHeight;if(document.documentElement&&document.documentElement.clientHeight)return document.documentElement.clientHeight;if(document.body&&document.body.clientHeight)return document.body.clientHeight}
function getScrollTop(){if(self.pageYOffset)return self.pageYOffset;if(document.documentElement&&document.documentElement.scrollTop)return document.documentElement.scrollTop;if(document.body)return document.body.scrollTop}function getScrollLeft(){if(self.pageXOffset)return self.pageYOffset;if(document.documentElement&&document.documentElement.scrollLeft)return document.documentElement.scrollLeft;if(document.body)return document.body.scrollLeft}
function hasStyleClass(a,b){return 0<=(" "+a.className+" ").indexOf(" "+b+" ")}function addStyleClass(a,b){0>(" "+a.className+" ").indexOf(" "+b+" ")&&(a.className+=a.className&&0<a.className.length?" "+b:b)}function delStyleClass(a,b){var c=" "+a.className+" ",d=b.length,e=c.indexOf(" "+b+" ");0<=e&&(d=e+d+1,a.className=trim(c.substring(0,e)+c.substring(d,c.length)))}function hiOn(a){null!=a&&addStyleClass(a,"highlight")}function hiOff(a){null!=a&&delStyleClass(a,"highlight")}
function toggleVis(a){a.style.visibility="hidden"==a.style.visibility?"visible":"hidden"}function toggleVisWithPositionAbsolute(a){if(a=document.getElementById(a))toggleVis(a),a.style.position="absolute"==a.style.position?"static":"absolute"}function setVis(a,b){a.style.visibility=b?"visible":"hidden"}
function toggleVisWIframe(a){var b=document.getElementById(a.id+"_iframe");"undefined"!=typeof b&&("hidden"==a.style.visibility?(b.style.left=a.offsetLeft,b.style.left==a.offsetLeft+"px"&&(b.style.top=a.offsetTop,b.style.width=a.offsetWidth,b.style.height=a.offsetHeight,b.style.display="block")):b.style.display="none");toggleVis(a)}function formatMessage(a){var b=arguments;return a.replace(/\{([0-9]*)\}/g,function(a,d){return b[parseInt(d)+1]})}
function highlightToc(a,b){top.frames.frames.body&&top.frames.body.frames.toc&&top.frames.body.frames.toc.document.getElementById("fullyLoadedDiv")&&top.frames.body.frames.toc.HTMLTreeNode.prototype.openHTMLTree(a,b)}function loadToc(a){var b=top.frames.body.frames.content.location.href,b=b.substring(b.lastIndexOf("/")+1,b.indexOf(".htm"));top.frames.body.frames.toc.location.href=a+"?item="+b+"&section=none"}
function deepCopy(a,b){var c=b.createElement(a.tagName);if("undefined"!=typeof a.attributes&&null!=a.attributes)for(var d=0;d<a.attributes.length;d++)c.setAttribute(a.attributes[d].name,a.attributes[d].value);null!=a.nodeValue&&c.appendChild(b.createTextNode(a.nodeValue));if("undefined"!=typeof a.childNodes&&null!=a.childNodes)for(d=0;d<a.childNodes.length;d++)c.appendChild(deepCopy(a.childNodes[d],b));return c}
function borrowForm(a,b,c){var a=document.getElementById(a),d=a.action,e=a.target;null!=b&&(a.action=b);null!=c&&(a.target=c);if(a.onsubmit)a.onsubmit();a.submit();a.action=d;a.target=e}function toggleRow(a,b){var c=document.getElementById(a);if(null!=c){for(;null!=c&&"TR"!=c.tagName;)c=c.parentNode;toggleDisplay(c,b)}}function setRowVis(a,b){var c=document.getElementById(a);if(null!=c){for(;null!=c&&"TR"!=c.tagName;)c=c.parentNode;null!=c&&setVis(c,b)}}
function toggleDisplay(a,b){null!=a&&(a.style.display=isIE&&!isOpera?b?"block":"none":b?"table-row":"none")}function toggleDisplayWithDisplayType(a,b,c){var d=document.getElementById(a);d&&(b||(b="block"),c?"none"==d.style.display?Sfdc.Effects.rollIn(d,function(){d.style.display=b}):Sfdc.Effects.rollOut(d):d.style.display="none"==d.style.display?b:"none")}function getElementsByNameCS(a){for(var b=document.getElementsByName(a),c=[],d=0;d<b.length;d++)b[d].name==a&&c.push(b[d]);return c}
function getElementByIdCS(a){return getElementByIdCSWithDoc(document,a)}function getElementByIdCSWithDoc(a,b){var c=a.getElementById(b);return null==c||c.id==b?c:a.all?a.all[b]:null}function dashify(a){return a.replace(/([a-z])([A-Z])/g,"$1-$2").toLowerCase()}function getCurrentStyle(a,b){var c;c=a.currentStyle?a.currentStyle[b]:document.defaultView&&document.defaultView.getComputedStyle?(c=document.defaultView.getComputedStyle(a,null))?c.getPropertyValue(dashify(b)):null:null;return c}
function copyAddr(a,b,c,d,e,f,g,k,l,h,j,m,n){document.getElementById(f).value=document.getElementById(a).value;document.getElementById(g).value=document.getElementById(b).value;document.getElementById(k).value=document.getElementById(c).value;document.getElementById(l).value=document.getElementById(d).value;if(n)document.getElementById(l).onchange();j&&m&&(document.getElementById(h).value=document.getElementById(e).value)}
function showMoreList(a,b,c){Sfdc.warn("Legacy Function showMoreList was called, use RelatedList.get(listId).showMoreList() instead.");RelatedList.get(c).showMoreList(a,b)}function callRelatedListAction(a,b,c,d,e,f){Sfdc.warn("Legacy Function callRelatedListAction was called, use RelatedList.get(listId).callRelatedListAction() instead.");RelatedList.get(d).callRelatedListAction(a,b,c,null,null,e,f)}
function setElementsEnabledBasedOnCheckbox(a,b){var c=document.getElementById(a);if(null!=c&&null!=b)for(var d=0;d<b.length;d++){var e=c,f=document.getElementById(b[d]);f&&(f.style.display=e.checked?"":"none")}}
function registerClickToDial(a,b){var c;if(self.getAccessibleParentWindow)c=getAccessibleParentWindow(self);else if(self.location.pathname==="/"+IFrameElement.EmptyRelatedListDoc)try{c=self.parent}catch(d){c=null}else c=self;c&&c.registerClickToDialEnabled&&(b?c.registerClickToDialEnabled(a):c.registerClickToDialDisabled(a))}function stripDomainFromUrl(a){var b=a.indexOf("://");-1!=b&&(a=a.substring(b+3),a=a.substring(a.indexOf("/")));return a}function bodyOnFocus(){}
isIE7&&window.attachEvent("onunload",function(){for(var a=document.body.getElementsByTagName("iframe"),b=0;b<a.length;b++)a[b].id&&"066"===a[b].id.substring(0,3)&&(a[b].src="javascript:false",a[b].parentNode.removeChild(a[b]))});